---
abstract: 'Test framework for Config::Model'
author:
  - 'Dominique Dumont'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.132140'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-Tester
requires:
  File::Copy::Recursive: 0
  File::HomeDir: 0
  Log::Log4perl: 1.11
  Path::Class: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::File::Contents: 0
  Test::Memory::Cycle: 0
  Test::More: 0
  Test::Warn: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Config-Model-Tester
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model-tester.git
version: 2.045
