---
abstract: 'Test framework for Config::Model'
author:
  - 'Dominique Dumont'
build_requires:
  Module::Build: '0.34'
configure_requires:
  Module::Build: '0.34'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Model-Tester
requires:
  File::Copy: '0'
  File::Copy::Recursive: '0'
  File::Find: '0'
  File::Path: '0'
  File::Spec: '0'
  Log::Log4perl: '1.11'
  Path::Class: '0.29'
  Test::Differences: '0'
  Test::Exception: '0'
  Test::File::Contents: '0'
  Test::Memory::Cycle: '0'
  Test::More: '0'
  Test::Warn: '0'
  perl: '5.010'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Config-Model-Tester
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model-tester.git
version: '2.048'
